---
layout: cv
title: Miguel Smith's CV
---
# Isaac Newton
Student, Chemist, Guitarist, Foodie, Music Lover

<div id="webaddress">
<a href="smi18055@byui.edu">smi18055@byui.edu</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Surviving physics courses

### Specialized in

Analytical Chemistry


### Research interests

Protein Mass Spectroscopy, Nanotechnology Instrumentation, Quantum Dots, finding obscure albums


## Education

Bachelor of Science, Chemistry
Minor: Data Science
Expected in 2026
Brigham Young University Idaho, Rexburg, ID

GED 
Clarke County High School
Berryville, VA



## Awards

Rotary Club of Clarke County, VA, Outstanding Student Award, `2018`
Boy Scouts of America, Eagle Scout, `2016`


## Publications

...buffering...buffering...grad school required...

### Journals

...buffering...

### Patents

...buffering...


## Occupation

`Jan 2025 – Present`
Lecture Teaching Assistant
• Teach students over ZOOM and assist a professor in CHEM101, Introduction to Chemistry.
• Readily answer questions while students perform their tasks and assess and adjust student
learning as needed.
• Build a climate of trust and responsiveness to students and the professor.
`April 2024– July 2024`
Laboratory Stockroom Assistant
• Stock, set up, and break down laboratory materials in preparation for various laboratory classes.
• Refill chemicals and materials in each laboratory in the Chemistry Department; carefully dispose of
heavy metal and organic chemical waste.
• Perform triplicate standardizing titrations to test concentration in-stock solutions for different laboratory
classes.
`Sept 2023 – July 2024`
Laboratory Teaching Assistant
• Assist professor, teach laboratory skills and methods, and answer student questions during and outside class.
• Prepare laboratory for experiments and coordinate instructional activities.
• Teach students lab safety, clean up, and chemical disposal protocols.




<!-- ### Footer

Last updated: May 2013 -->